repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-added-large-files
    -   id: check-json
    -   id: pretty-format-json
    -   id: requirements-txt-fixer
-   repo: https://github.com/pre-commit/mirrors-yapf
    rev: 'v0.31.0'
    hooks:
    -   id: yapf
        args: [-i, --style, .style.yapf]
- repo: https://github.com/myint/autoflake
  rev: 'v1.4'
  hooks:
   - id: autoflake
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v2.5.0
    hooks:
    -   id: reorder-python-imports
        args: [--py36-plus]
- repo: https://github.com/pre-commit/pygrep-hooks
  rev: 'v1.9.0'
  hooks:
    - id: python-use-type-annotations
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.902
    hooks:
    -   id: mypy
- repo: https://github.com/pycqa/flake8
  rev: '3.9.2'
  hooks:
    - id: flake8
      args: [--config=.flake8]
      exclude: ^(.bson|.qml|tests.py)|__init__.py|tests/
      additional_dependencies: [flake8-docstrings]
